### ISSUE TITLE
runing kafka-mirror-maker has "java.lang.NoSuchMethodError: kafka.consumer.BaseConsumerRecord.headers()Lorg/apache/kafka/common/header/Headers;" ERROR

### ISSUE THREAD

**Issue by disusu** [slavirok/mirrormaker-rename-topic-handler#1]
`[2019-03-13 10:15:22,339] FATAL [mirrormaker-thread-0] Mirror maker thread failure due to  (kafka.tools.MirrorMaker$MirrorMakerThread)
java.lang.NoSuchMethodError: kafka.consumer.BaseConsumerRecord.headers()Lorg/apache/kafka/common/header/Headers;
        at com.slavirok.RenameTopicHandler.handle(RenameTopicHandler.java:27)
        at kafka.tools.MirrorMaker$MirrorMakerThread.run(MirrorMaker.scala:433)
[2019-03-13 10:15:22,369] FATAL [mirrormaker-thread-0] Mirror maker thread exited abnormally, stopping the whole mirror maker. (kafka.tools.MirrorMaker$MirrorMakerThread)`

**Comment by chaicesan** [comment]
Did you manage to fix this @disusu

**Comment by daluu** [comment]
I wonder if this has anything to do with version compatibility between kafka broker, mirror maker, and this codebase. I ran into this just recently using the [parent/base repo](https://github.com/opencore/mirrormaker_topic_rename) that this repo was based off of. But things used to work for me, for kafka v0.10.1.1 or at least v0.8.2.1 for mirror maker, and master branch of this codebase, and not sure about the source and target cluster's kafka broker versions.

For debugging, may want to indicate the versions of the various components affected/used.
